[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/feap_editor", "crates/feap_license"]


[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
chrono = { version = "0.4" }
rand = { version = "0.9" }
